from __future__ import annotations

_VENDOR_TYPE_MAP: list[tuple[str, str]] = [
    # IP cameras
    ("hikvision",  "iot_camera"),
    ("reolink",    "iot_camera"),
    ("dahua",      "iot_camera"),
    ("axis",       "iot_camera"),
    ("hanwha",     "iot_camera"),
    ("vivotek",    "iot_camera"),
    ("foscam",     "iot_camera"),
    ("uniview",    "iot_camera"),
    ("tiandy",     "iot_camera"),
    # Routers / gateways / APs
    ("tp-link",    "router"),
    ("tplink",     "router"),
    ("asus",       "router"),
    ("netgear",    "router"),
    ("d-link",     "router"),
    ("dlink",      "router"),
    ("mikrotik",   "router"),
    ("ubiquiti",   "router"),
    ("cisco",      "router"),
    ("zyxel",      "router"),
    ("huawei",     "router"),
    ("keenetic",   "router"),
    ("zte",        "router"),
    ("technicolor","router"),
    ("aruba",      "router"),
    ("ruckus",     "router"),
    ("extreme networks", "router"),
    # IoT sensors / MCUs
    ("espressif",  "iot_sensor"),
    ("arduino",    "iot_sensor"),
    ("raspberry",  "iot_sensor"),
    ("particle",   "iot_sensor"),
    ("tuya",       "iot_sensor"),
    ("nordic semi","iot_sensor"),
    ("texas instruments", "iot_sensor"),
    # Smart lights
    ("philips",    "iot_bulb"),
    ("signify",    "iot_bulb"),
    ("lifx",       "iot_bulb"),
    ("yeelight",   "iot_bulb"),
    ("nanoleaf",   "iot_bulb"),
    # Smart plugs
    ("tp-link kasa", "iot_plug"),
    # PCs / laptops
    ("microsoft",  "pc_windows"),
    ("dell",       "pc_windows"),
    ("hewlett",    "pc_windows"),
    (" hp ",       "pc_windows"),
    ("lenovo",     "pc_windows"),
    ("intel",      "pc_windows"),
    ("realtek",    "pc_windows"),
    ("gigabyte",   "pc_windows"),
    ("asustek",    "pc_windows"),
    ("acer",       "pc_windows"),
    ("toshiba",    "pc_windows"),
    ("msi",        "pc_windows"),
    ("pegatron",   "pc_windows"),
    ("compal",     "pc_windows"),
    ("wistron",    "pc_windows"),
    ("quanta",     "pc_windows"),
    # Apple
    ("apple",      "pc_mac"),
    # Linux / servers
    ("canonical",  "pc_linux"),
    ("supermicro", "pc_linux"),
    ("vmware",     "pc_linux"),
    ("xensource",  "pc_linux"),
    # Phones / tablets
    ("samsung",    "phone"),
    ("xiaomi",     "phone"),
    ("oneplus",    "phone"),
    ("oppo",       "phone"),
    ("vivo",       "phone"),
    ("huawei device", "phone"),
    ("honor",      "phone"),
    ("realme",     "phone"),
    ("google",     "phone"),
    ("motorola",   "phone"),
    ("zte mobile", "phone"),
    ("htc",        "phone"),
    ("lg electronics mobile", "phone"),
    # Printers
    ("xerox",      "printer"),
    ("canon",      "printer"),
    ("epson",      "printer"),
    ("brother",    "printer"),
    ("lexmark",    "printer"),
    ("ricoh",      "printer"),
    ("kyocera",    "printer"),
    ("konica",     "printer"),
    # NAS
    ("synology",   "nas"),
    ("qnap",       "nas"),
    ("western digital", "nas"),
    ("seagate",    "nas"),
    # Game consoles
    ("nintendo",   "game_console"),
    ("sony interactive", "game_console"),
    ("microsoft xbox", "game_console"),
    # Smart TVs
    ("lg electronics", "tv"),
    ("samsung tv", "tv"),
    ("sony",       "tv"),
    ("hisense",    "tv"),
    ("tcl",        "tv"),
    ("skyworth",   "tv"),
]

# Patterns checked against the SHORT hostname (first label of FQDN, lowercased).
# Tuples: (substring_or_prefix, device_type, require_prefix=False)
# Use exact substring match — order matters (more specific first).
_HOSTNAME_RULES: list[tuple[str, str]] = [
    # Apple
    ("macbook",    "pc_mac"),
    ("macmini",    "pc_mac"),
    ("imac",       "pc_mac"),
    ("mac-",       "pc_mac"),
    ("iphone",     "phone"),
    ("ipad",       "phone"),
    ("appletv",    "tv"),
    # Windows PC (common autogenerated names)
    ("desktop-",   "pc_windows"),
    ("desktop_",   "pc_windows"),
    ("laptop-",    "pc_windows"),
    ("laptop_",    "pc_windows"),
    ("notebook",   "pc_windows"),
    ("win-",       "pc_windows"),
    ("win10",      "pc_windows"),
    ("win11",      "pc_windows"),
    # "-pc" / "_pc" suffix / "pc-" prefix (e.g. tobitrowb-pc, DF-PC, PC-OFFICE)
    ("-pc",        "pc_windows"),
    ("_pc",        "pc_windows"),
    ("pc-",        "pc_windows"),
    ("pc_",        "pc_windows"),
    # Generic PC keywords
    ("workstation","pc_windows"),
    ("komputer",   "pc_windows"),   # Polish
    ("computer",   "pc_windows"),
    # Linux
    ("server",     "pc_linux"),
    ("srv-",       "pc_linux"),
    ("ubuntu",     "pc_linux"),
    ("debian",     "pc_linux"),
    ("fedora",     "pc_linux"),
    ("centos",     "pc_linux"),
    ("linux",      "pc_linux"),
    ("raspberry",  "iot_sensor"),
    ("rpi",        "iot_sensor"),
    ("pi-",        "iot_sensor"),
    ("esp",        "iot_sensor"),
    ("arduino",    "iot_sensor"),
    ("sensor",     "iot_sensor"),
    # Cameras
    ("cam",        "iot_camera"),
    ("camera",     "iot_camera"),
    ("ipcam",      "iot_camera"),
    ("nvr",        "iot_camera"),
    ("dvr",        "iot_camera"),
    # Network
    ("router",     "router"),
    ("gateway",    "router"),
    ("ap-",        "router"),
    ("wifi",       "router"),
    # Phones
    ("android",    "phone"),
    ("pixel",      "phone"),
    ("galaxy",     "phone"),
    ("huawei",     "phone"),
    ("honor",      "phone"),
    ("xiaomi",     "phone"),
    # Smart home
    ("hue",        "iot_bulb"),
    ("lifx",       "iot_bulb"),
    ("yeelight",   "iot_bulb"),
    ("plug",       "iot_plug"),
    # NAS
    ("diskstation","nas"),
    ("nas",        "nas"),
    # Printers
    ("printer",    "printer"),
    # Game consoles
    ("ps4",        "game_console"),
    ("ps5",        "game_console"),
    ("xbox",       "game_console"),
    ("playstation","game_console"),
    # TVs
    ("bravia",     "tv"),
    ("firetv",     "tv"),
    ("fire-tv",    "tv"),
    ("roku",       "tv"),
    ("smarttv",    "tv"),
]

_PORT_TYPE_MAP: dict[int, str] = {
    554:  "iot_camera",   # RTSP
    8554: "iot_camera",
    22:   "pc_linux",     # SSH
    3389: "pc_windows",   # RDP
    445:  "pc_windows",   # SMB
    9100: "printer",      # JetDirect
    631:  "printer",      # IPP
    548:  "pc_mac",       # AFP
    5009: "pc_mac",       # AirPlay
}


def _short_hostname(hostname: str) -> str:
    """Return first label of FQDN in lowercase: 'DF-PC.main.sgu.ru' → 'df-pc'."""
    return hostname.split(".")[0].lower().strip()


def guess_device_type(
    vendor: str = "",
    hostname: str = "",
    open_ports: list[int] | None = None,
) -> str:
    v = vendor.lower()
    h_full = hostname.lower()
    h = _short_hostname(hostname)   # first label of FQDN
    ports = open_ports or []

    # 1. Vendor match (most authoritative)
    for kw, dtype in _VENDOR_TYPE_MAP:
        if kw in v:
            return dtype

    # 2. Hostname match against short label first, then full hostname
    for pattern, dtype in _HOSTNAME_RULES:
        if pattern in h or pattern in h_full:
            return dtype

    # 3. Port-based fallback
    for port in ports:
        mapped = _PORT_TYPE_MAP.get(port)
        if mapped:
            return mapped

    return "unknown"
